Add Snaps diagrams
MetaMask/metamask-docs pull request #1123
Opened 2024-02-05 23:44 UTC by alexandratran

Add simple diagrams for Snaps architecture and key generation. Fixes #1101.

2024-02-06 02:05 UTC, Montoya commented on snaps/assets/snaps-architecture.png
Excellent

2024-02-06 02:06 UTC, Montoya requested changes

2024-02-06 02:06 UTC, Montoya commented on snaps/assets/snaps-getentropy.png
These should be one way arrows, not two way. Just going from left to right.

2024-02-06 02:06 UTC, Montoya commented on snaps/concepts/overview.md
> +The following diagram illustrates how Snaps can derive users' keys using
I would just say "derive keys" not "derive users' keys"

2024-02-06 10:49 UTC, FrederikBolding commented on snaps/assets/snaps-getentropy.png
Wondering if we should make some changes to the diagram to make it clearer that the snap does not access the SRP?

2024-02-06 14:44 UTC, Montoya commented on snaps/assets/snaps-getentropy.png
Could just add a callout below the image saying "Note that Snaps cannot access the user's Secret Recovery Phrase. Snaps can only derive keys using the provided methods. Furthermore, Snaps cannot derive Ethereum keys (`coinType:60`) and any Snap that derives keys must receive a security audit before it can be made available to users."

2024-02-06 18:57 UTC, alexandratran commented on snaps/assets/snaps-getentropy.png
@Montoya I've added this note.

2024-02-07 04:50 UTC, Montoya approved these changes

2024-02-07 18:53 UTC, joaniefromtheblock approved these changes
lgtm

2024-02-07 19:10 UTC, merged