Document the Snaps static file API
MetaMask/metamask-docs pull request #1138
Opened 2024-02-14 19:04 UTC by ziad-saab

Fixes MetaMask/metamask-planning#1491

2024-02-14 19:05 UTC, ziad-saab commented
**TODO**: Add feature icon

2024-02-14 19:47 UTC, Montoya requested changes
Wording

2024-02-14 19:47 UTC, Montoya commented on snaps/index.mdx
> +      description: "Lazy-load static files like Wasm modules or ZK keys"
"Wasm modules or ZK circuits" not "keys"

2024-02-14 19:47 UTC, Montoya commented on snaps/how-to/handle-static-files.md
> +The Snaps platform provides a static file API that is useful to load Wasm modules, ZK keys, or anything else that needs to be lazily loaded.
"ZK circuits,"

2024-02-14 19:48 UTC, Montoya commented
> Preview published: [zs/snap-getfile](https://docs.metamask.io/zs/snap-getfile/)

I don't know why the icon does not show up in this build

2024-02-14 20:04 UTC, ziad-saab commented
> > Preview published: [zs/snap-getfile](https://docs.metamask.io/zs/snap-getfile/)
> 
> I don't know why the icon does not show up in this build

It definitely shows up for me. It's a base64 URL.

2024-02-15 05:22 UTC, alexandratran approved these changes
Moved this into the new "features" category and made some edits to related content. LGTM.

2024-02-15 14:39 UTC, merged