Add how-to on restricting rpc apis by URL
MetaMask/metamask-docs pull request #1223
Opened 2024-03-18 23:02 UTC by ziad-saab

closes MetaMask/MetaMask-planning#1285.

2024-03-19 03:04 UTC, Montoya commented
I think the tutorial should use the URL library like so: https://codepen.io/m0nt0y4/pen/WNLxYGw

Relying on `Array.prototype.includes()` will miss if the origin is "https://metamask.io" and the array contains "https://metamask.io/" or if the origin is "https://metamask.io/dapp/" and the array contains "https://metamask.io". The point of using the URL library is the extract the most important parts of the origin (protocol + top level domain) and key based on that. Then you can just store the TLD in the array and compare against that, and require the request to always come from https. Or store both protocol + TLD in the array and compare against both.

2024-03-19 03:04 UTC, Montoya requested changes
See above

2024-03-19 03:09 UTC, Montoya commented on snaps/how-to/restrict-rpc-api.md
> +
Is there supposed to be `case 'secureMethod':` here?

2024-03-19 03:10 UTC, Montoya commented on snaps/reference/permissions.md
>  Alternatively, you can specify the caveat `allowedOrigins` to restrict requests to specific domains or Snap IDs.
Maybe this should say "to restrict **all** requests" to differentiate from the guide we are adding

2024-03-19 03:11 UTC, Montoya commented on snaps/how-to/restrict-rpc-api.md
> +## All Dapps are allowed by default
Dapps should be lowercase like dapps

2024-03-19 03:11 UTC, Montoya requested changes

2024-03-19 03:11 UTC, Montoya commented on snaps/how-to/restrict-rpc-api.md
> +By default, a Snap's RPC API is callable by any Dapp if the [`dapps` caveat to `endowment:rpc`](../reference/permissions.md#endowmentrpc) is set to `true` in the Snap's manifest.
any **dapp**

2024-03-19 07:39 UTC, ziad-saab commented
> Relying on `Array.prototype.includes()` will miss if the origin is "https://metamask.io" and the array contains "https://metamask.io/" or if the origin is "https://metamask.io/dapp/" and the array contains "https://metamask.io".

@Montoya it's my understanding and experience that the `origin` parameter is already just protocol + domain. it doesn't contain any path information. Do we still think it's necessary to include the URL manipulation in this case?

2024-03-20 22:13 UTC, Montoya commented
@ziad-saab Oh, maybe my understanding is wrong. If that is true then this approach should work fine.

2024-03-21 03:28 UTC, alexandratran approved these changes
Minor edits to content. LGTM.

2024-03-21 04:30 UTC, Montoya approved these changes

2024-03-21 04:30 UTC, merged