Add signature insights documentation
MetaMask/metamask-docs pull request #1228
Opened 2024-03-21 23:51 UTC by ziad-saab

2024-03-22 01:51 UTC, Montoya requested changes

2024-03-22 01:51 UTC, Montoya commented on snaps/features/signature-insights.md
> +Your Snap should use `signatureMethod` as the source of the truth to identify the signature scheme it is providing insights for.
as the source ~~of~~ truth

2024-03-22 02:08 UTC, Montoya approved these changes

2024-03-25 20:31 UTC, alexandratran approved these changes
Edited content and reordered entry points reference to be in alphabetical order. LGTM.

2024-03-25 22:22 UTC, merged