Update video formatting
MetaMask/metamask-docs pull request #1234
Opened 2024-03-26 20:22 UTC by joaniefromtheblock

Closes #1072

2024-03-30 20:40 UTC, alexandratran requested changes
To close issue #1072, this PR still needs to address the first two points described in that issue:

1. Relocate videos in the `static` folder to fix the PR preview issue.
2. Fix the rendering of the Unity SDK video and make it consistent with the other YouTube embeds.

Please let me know if you have questions or blockers.

2024-04-01 21:41 UTC, alexandratran requested changes
Please always check previews locally and on the PR.

To match how we organize images, can we add a `wallet/assets/videos` folder and `snaps/assets/video` folder and add the corresponding videos in those folders? Then update the video src links and check that they render properly. I'm not sure if relative or absolute links are better to use in this case.

2024-04-01 21:41 UTC, alexandratran commented on wallet/how-to/use-sdk/gaming/unity/index.md
> +  <YoutubeEmbed url='https://www.youtube.com/embed/0D1cIH-PZtI' />
This does not appear in the rendered preview and requires an import statement at the top of the page:

```
import YoutubeEmbed from '@site/src/components/YoutubeEmbed';
```

2024-04-01 21:41 UTC, alexandratran commented on wallet/concepts/sdk/index.md
> +    <source src="/public-videos/sdk-desktop.mp4" type="video/mp4" />
These links don't match the folder name you created `public_videos` and so don't render in the preview

2024-04-04 16:53 UTC, Montoya approved these changes

2024-04-10 20:58 UTC, closed without merging