Document using node.js modules in Snaps
MetaMask/metamask-docs pull request #1238
Opened 2024-03-29 22:50 UTC by alexandratran

This PR slightly rearranges the "Snaps execution environment" concept page and adds a note on how to use the Node.js built-in modules, which are not supported by default. Fixes #855.

2024-03-29 23:14 UTC, Mrtenz requested changes
There is a `polyfills` option in the config which doesn't require changing the Webpack config. Looks like we forgot to add this to the CLI's README 😅

2024-03-30 10:30 UTC, Mrtenz approved these changes

2024-04-01 03:25 UTC, joaniefromtheblock commented on snaps/reference/cli/options.md
> +See [the list of available polyfills](https://github.com/MetaMask/snaps/blob/51a1d04ea50c5c286262df1959ef0b1ced84b6e2/packages/snaps-cli/src/config.ts#L383-L416).
I think this is a fragment

```suggestion
For more information, see [the list of available polyfills](https://github.com/MetaMask/snaps/blob/51a1d04ea50c5c286262df1959ef0b1ced84b6e2/packages/snaps-cli/src/config.ts#L383-L416).
```

2024-04-01 03:28 UTC, joaniefromtheblock commented on snaps/learn/about-snaps/execution-environment.md
> +This allows you to safely execute Snaps anywhere, without the Snap needing to worry about where and
I think uses anthropomorphism (e.g. worry). Maybe the following instead?

```suggestion
This ensures that Snaps can be executed safely in any environment, without needing to consider their execution context or method.
```

2024-04-01 03:28 UTC, joaniefromtheblock approved these changes
LGTM

2024-04-01 18:06 UTC, merged