Document Snaps notifications
MetaMask/metamask-docs pull request #1292
Opened 2024-04-29 21:32 UTC by alexandratran

# Description

Add feature page for Snaps notifications.

## Issue(s) fixed

Fixes #1261

## Preview

## Checklist

Complete this checklist before merging your PR:

- [x] If this PR contains a major change to the documentation content, I have added an entry to the top of the ["What's new?"](https://github.com/MetaMask/metamask-docs/blob/main/docs/whats-new.md) page.
- [ ] The proposed changes have been reviewed and approved by a member of the documentation team.

2024-04-29 22:03 UTC, Montoya requested changes

2024-04-29 22:03 UTC, Montoya commented on snaps/index.mdx
> +      description: "Notify users directly in MetaMask, or natively in their browser."
I do not know if it is correct to change the last word. Browser notification APIs are displayed in the OS. They are not displayed in the browser. The Chrome spec says they are displayed in the system tray: https://developer.chrome.com/docs/extensions/reference/api/notifications

2024-04-29 22:03 UTC, Montoya commented on snaps/reference/snaps-api.md
> +Displays a [notification](../features/notifications.md) in MetaMask or natively in the browser.
Last word is probably a mistake, should be OS.

2024-04-30 01:23 UTC, alexandratran commented on snaps/features/notifications.md
> +We recommend using `type: "inApp"` because there's no guarantee that native notifications are
Can you expand on this?

2024-04-30 18:14 UTC, Montoya approved these changes

2024-05-01 01:27 UTC, bgravenorst approved these changes
lgtm

2024-05-01 05:22 UTC, merged