feat(docs): act-1448 - added sentry plugin
MetaMask/metamask-docs pull request #1408
Opened 2024-07-11 09:59 UTC by TrofimovAnton85

## Description

- Added sentry plugin to record user Interactions (only for prod)

## Links

https://infura.atlassian.net/browse/ACT-1448

2024-07-12 15:39 UTC, Vt2049 approved these changes
👍

2024-07-12 15:44 UTC, Vt2049 approved these changes

2024-07-16 12:53 UTC, cedricmagne requested changes

2024-07-16 12:53 UTC, cedricmagne commented on src/components/ParserOpenRPC/index.tsx
> +  console.log("connected_acc", connected, account);
Could you remove console.log

2024-07-16 13:23 UTC, TrofimovAnton85 commented on src/components/ParserOpenRPC/index.tsx
> +  console.log("connected_acc", connected, account);
fixed in last commit!

2024-07-16 14:07 UTC, aednikanov approved these changes

2024-07-16 16:45 UTC, alexandratran approved these changes

2024-07-17 09:58 UTC, cedricmagne approved these changes

2024-07-17 09:58 UTC, cedricmagne commented on src/components/ParserOpenRPC/InteractiveBox/templates/BaseInputTemplate.tsx
<img width="686" alt="Screenshot 2024-07-17 at 11 51 34" src="https://github.com/user-attachments/assets/e5732e9b-623d-43ac-828d-1b8a71e7de32">

If you can just change : 
```
inputValue >= 1
```
by : 
```
Number(inputValue) >= 1
```

2024-07-17 10:13 UTC, merged