Fix workflows, fix lint issues, make npm default manager
MetaMask/metamask-docs pull request #1563
Opened 2024-09-19 08:55 UTC by Voltmod

Fix workflows, fix lint issues, make npm default manager

2024-09-19 08:59 UTC, TrofimovAnton85 approved these changes

2024-09-19 09:13 UTC, aednikanov approved these changes

2024-09-19 09:32 UTC, cedricmagne approved these changes

2024-09-23 08:54 UTC, TrofimovAnton85 approved these changes

2024-09-23 09:08 UTC, aednikanov submitted a review, later dismissed

2024-09-23 16:10 UTC, cedricmagne requested changes
Need to update : 

- src/theme/DocItem/Footer/index.jsx
- src/theme/DocItem/Layout/index.jsx
- src/theme/DocItem/Tags/index.jsx

With -> import { useDoc } from "@docusaurus/plugin-content-docs/client";

2024-09-26 20:28 UTC, alexandratran submitted a review, later dismissed

2024-09-27 08:19 UTC, cedricmagne approved these changes

2024-09-27 09:32 UTC, TrofimovAnton85 approved these changes

2024-09-27 09:57 UTC, cedricmagne approved these changes

2024-09-27 10:42 UTC, joaniefromtheblock approved these changes

2024-09-27 10:43 UTC, merged