Add new network support
MetaMask/metamask-docs pull request #1776
Opened 2024-12-16 00:26 UTC by bgravenorst

# Description

Add Infura support for Swellchain network

## Preview

## Checklist

Complete this checklist before merging your PR:

- [x] If this PR contains a major change to the documentation content, I have added an entry to the top of the ["What's new?"](https://github.com/MetaMask/metamask-docs/blob/main/docs/whats-new.md) page.
- [x] The proposed changes have been reviewed and approved by a member of the documentation team.

2024-12-16 19:17 UTC, alexandratran submitted a review, later dismissed
LGTM.

2024-12-17 05:06 UTC, twhay requested changes
- debug_accountRange requires a change to the example curl request in order to prevent an error from returning

2024-12-19 00:49 UTC, alexandratran approved these changes

2024-12-19 01:06 UTC, twhay approved these changes
Changes look good to me!

2024-12-19 01:07 UTC, merged