Added links to template Snap and 5-Minute tutorial
MetaMask/metamask-docs pull request #437
Opened 2022-03-25 18:09 UTC by Montoya

Added two more resources at the bottom of the Snaps Development Guide

2022-03-25 18:10 UTC, Montoya commented
I don't know if the HTML has to be rebuilt... I just modifided the markdown files

2022-03-28 21:17 UTC, rekmarks requested changes

2022-03-28 21:17 UTC, rekmarks commented on docs/guide/snaps-development-guide.md
> +- [Template Snap Repository](https://github.com/MetaMask/template-snap)
This is already linked to extensively throughout the page.
```suggestion
```

2022-03-29 00:41 UTC, rekmarks approved these changes

2022-03-29 00:50 UTC, merged