Add snaps exports documentation
MetaMask/metamask-docs pull request #551
Opened 2022-09-22 14:35 UTC by GuillaumeRx

Fixes https://github.com/MetaMask/snaps-monorepo/issues/771

2022-09-22 17:07 UTC, hmalik88 commented on docs/guide/snaps-exports.md
> +In order to communicate with the outside world, the snap must implement its own JSON-RPC API by exposing an exported function called `onRpcRequest`. Whenever the snap receives a JSON-RPC request from
```suggestion
In order to communicate with dApps and other snaps, the snap must implement its own JSON-RPC API by exposing an exported function called `onRpcRequest`. Whenever the snap receives a JSON-RPC request, the `onRpcRequest` handler function will be called with the below parameters.
```

2022-09-22 17:16 UTC, hmalik88 commented on docs/guide/snaps-exports.md
> +If the snap whats to provide transactions insights before they are accepted for signing by the uses, the snap must export a function called `onTransaction`. Whenever a transaction is submited to the
```suggestion
If the snap wants to provide transaction insights before a user signs a transaction, the snap must export a function called `onTransaction`. Whenever there is a contract interaction and a transaction is submitted via the extension, this function will be called. The raw unsigned transaction payload will be passed to the `onTransaction` handler function.
```

2022-09-23 11:30 UTC, ritave requested changes

2022-09-23 11:30 UTC, ritave commented on docs/guide/snaps-exports.md
> +  request: JsonRpcRequest<unknown[] | { [key: string]: unknown }>;
`JsonRpcRequest` is not defined anywhere in the documentation

2022-09-23 11:30 UTC, ritave commented on docs/guide/snaps-exports.md
> +
Please add an example section. Both Typescript and Javascript

2022-09-23 11:30 UTC, ritave commented on docs/guide/snaps-exports.md
> +type RpcHandlerReturn = Promise<unknown>;
`Promise<unknown> | unknown`

2022-09-23 11:30 UTC, ritave commented on docs/guide/snaps-exports.md
> +  transaction: Record<string, unknown>;
We don't explain the transaction anywhere in the documentation. We could at least direct people to [SIP-3](https://metamask.github.io/SIPs/SIPS/sip-3) apendix.

2022-09-23 11:30 UTC, ritave commented on docs/guide/snaps-exports.md
> +- `onTransactionArgs` - the raw transaction payload and the [CAIP2](https://github.com/ChainAgnostic/CAIPs/blob/master/CAIPs/caip-2.md) chain ID.
```suggestion
- `onTransactionArgs` - the raw transaction payload and the [CAIP-2 chain ID](https://github.com/ChainAgnostic/CAIPs/blob/master/CAIPs/caip-2.md).
```

2022-09-23 11:30 UTC, ritave commented on docs/guide/snaps-exports.md
> +type onTransactionHandlerReturn = Promise<onTransactionResponse>;
```suggestion
type onTransactionHandlerReturn = Promise<OnTransactionResponse>;
```

2022-09-23 11:30 UTC, ritave commented on docs/guide/snaps-exports.md
> +```typescript
Why are those separate code blocks?

2022-09-23 11:30 UTC, ritave commented on docs/guide/snaps-exports.md
> +- `onTransactionResponse` - The `insights` object returned by the snap will be displayed alongside the confirmation for the transaction that `onTransaction` was called with. Keys and values will be d
Please add an example section.

2022-09-23 11:30 UTC, ritave commented on docs/guide/snaps-permissions.md
> +For snaps that provides transaction insights, the snap can request the `endowment:transaction-insight` permission. This permission grants a snap read-only access to raw transaction payloads, before t
Direct to `snap-exports.md` for more details?

2022-09-25 15:21 UTC, hmalik88 submitted a review, later dismissed
LGTM.

2022-09-26 14:15 UTC, ritave approved these changes

2022-09-26 14:15 UTC, ritave commented on docs/guide/snaps-exports.md
> +export const onRpcRequest: OnRpcRequestHandler = ({ origin, request }) => {
For consistency with JS version.

```suggestion
export const onRpcRequest: OnRpcRequestHandler = async ({ origin, request }) => {
```

2022-09-26 14:15 UTC, ritave commented on docs/guide/snaps-exports.md
> +type onTransactionHandlerReturn = Promise<OnTransactionResponse>;
```suggestion
type OnTransactionHandlerReturn = Promise<OnTransactionResponse>;
```

2022-09-26 14:40 UTC, hmalik88 submitted a review, later dismissed

2022-09-26 15:00 UTC, ritave approved these changes

2022-09-26 15:28 UTC, ritave approved these changes

2022-09-26 15:28 UTC, ritave submitted a review, later dismissed

2022-09-26 15:29 UTC, ritave commented
Wtf. Why can you multiple approve.

2022-09-27 08:19 UTC, jlwllmr commented on docs/guide/snaps-permissions.md
> +For snaps that provides transaction insights, the snap can request the `endowment:transaction-insight` permission. This permission grants a snap read-only access to raw transaction payloads, before t
'provides' -> provide

2022-09-27 08:22 UTC, jlwllmr requested changes
A few minor suggestions!

2022-09-27 08:24 UTC, jlwllmr commented on docs/guide/snaps-exports.md
> +In order to communicate with dApps and other snaps, the snap must implement its own JSON-RPC API by exposing an exported function called `onRpcRequest`. Whenever the snap receives a JSON-RPC request,
In line 20 we use 'dapp' (uncapitalised) -- suggest you decide on one for consistency

2022-09-27 10:58 UTC, jlwllmr commented on docs/guide/snaps-exports.md
> +Well, no, that's also up to you! If your snap can do something useful without receiving and responding to JSON-RPC requests, then you can skip exporting onRpcRequest. However, if you want to do somet
need to remove the 'e.g.' here

2022-09-27 10:58 UTC, jlwllmr requested changes
Just one minor thing to amend

2022-09-27 12:42 UTC, jlwllmr approved these changes
👍

2022-09-27 13:36 UTC, GuillaumeRx commented
Waiting on the Flask release that will contain transactions insights for Snaps to merge.

2022-11-01 19:11 UTC, merged