Add temporary docs homepage
MetaMask/metamask-docs pull request #748
Opened 2023-05-03 23:24 UTC by alexandratran

Add temporary docs homepage as starting point for a more fleshed out developer hub homepage. This may help visualize what content and sections are possible and needed for the homepage.

2023-05-04 08:25 UTC, bgravenorst commented on src/components/SnapsSection.tsx
> +    link: "/snaps/reference/cli",
This appears to link to the CLI, not APIs.

2023-05-04 20:29 UTC, ziad-saab requested changes
the temp homepage looks good! i have a few code wishes:

1. can the code in `custom.css` be modularized as `custom.module.css` as well?
2. can the `CardItem` type and the `Card` component, which are currently duplicated, be made into a custom component and re-used in both site sections

lmk what you think

2023-05-07 19:04 UTC, ziad-saab approved these changes

2023-05-08 23:12 UTC, bgravenorst approved these changes
LGTM. See minor suggestion.

2023-05-18 02:04 UTC, vandan approved these changes
Looks good to me from the perspective of having MVP content and a unified entry point for developers. Someone more technical should review the react code though.

2023-05-18 14:18 UTC, shanejonas approved these changes

2023-05-18 17:30 UTC, merged